name: Add a project
description: Use this form to add a new project to the Kudos Portal.

title: "[Add a project]"

labels: ["add-project"]

body:
  - type: input
    id: name
    attributes:
      label: Project Name
      description: "Enter the name of the project."
      placeholder: "Kudos"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: Slug
      description: "Enter a slug for the project."
      placeholder: "kudos"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a description of the project."
      placeholder: "A Portal for Agile Devtime..."
    validations:
      required: true

  - type: textarea
    id: websites
    attributes:
      label: Websites
      description: "On each new line write the website URLs."
      placeholder: "https://morekudos.com"

  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: "On each new line write the documentation URLs with a front end friendly label."
      placeholder: "GitHub Docs - https://github.com/kudos-ink/docs"

  - type: textarea
    id: explorers
    attributes:
      label: Explorers
      description: "On each new line write the explorer URLs with a front end friendly label."
      placeholder: "Subscan - https://polkadot.subscan.io/"

  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description: "On each new line write the repository URLs with a front end friendly label."
      placeholder: "Kudos Portal - https://github.com/kudos-ink/portal"
    validations:
      required: true

  - type: textarea
    id: social
    attributes:
      label: Social Media
      description: "On each new line write the social media URLs with a front end friendly label."
      placeholder: "X/Twitter - https://x.com/KudosPortal"

  - type: textarea
    id: networks
    attributes:
      label: Networks
      description: "On each new line write the relevant networks."
      placeholder: "Polkadot\nEthereum\nAstar"

  - type: checkboxes
    id: purposes
    attributes:
      label: Purposes
      description: "Select the purposes."
      options:
        - label: ai
        - label: bridge
        - label: dao
        - label: data
        - label: defi
        - label: evm
        - label: gaming
        - label: governance
        - label: nft
        - label: oracles
        - label: rwa
        - label: socialfi
        - label: staking
        - label: testing
        - label: universal

  - type: checkboxes
    id: stackLevels
    attributes:
      label: Stack Levels
      description: "Enter stack levels separated by commas."
      options:
        - label: protocol
        - label: runtime
        - label: smart-contract
        - label: messaging
        - label: offchain

  - type: checkboxes
    id: technologies
    attributes:
      label: Technologies
      description: "Select the technologies used."
      options:
        - label: substrate
        - label: ink
        - label: evm

  - type: checkboxes
    id: types
    attributes:
      label: Types
      description: "Select the types."
      options:
        - label: platform
        - label: tool
        - label: library
        - label: client
        - label: framework
        - label: template
        - label: mobile
        - label: service
        - label: dApp

  - type: checkboxes
    id: rewards
    attributes:
      label: Rewards
      options:
        - label: "The project can pay rewards to contributors."
