name: Process Issue Form Submission

on:
  issues:
    types: [opened, edited]

jobs:
  generate_json:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'add-project')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install JSON Schema Validator and Formats
        run: |
          npm install -g ajv-cli ajv-formats

      - name: Extract Issue Form Data and Generate JSON
        id: generate_json
        run: |
          # Save the issue body to a file
          echo "${{ github.event.issue.body }}" > issue_body.md

          # Run the external script to process the issue and generate JSON
          node scripts/process-issue.js issue_body.md

      - name: Validate JSON File
        run: |
          # Ensure the schema.json file is in the correct path
          ajv -c ajv-formats validate -s schema.json -d "data/projects/${{ steps.generate_json.outputs.slug }}.json" --strict=false

      - name: Create or Switch to Existing Branch and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          BRANCH_NAME="add-${{ steps.generate_json.outputs.slug }}"

          git fetch origin

          if git rev-parse --verify "${BRANCH_NAME}"; then
            git branch -D "${BRANCH_NAME}"
          fi

          if git ls-remote --heads origin "${BRANCH_NAME}" | grep "${BRANCH_NAME}"; then
            git push origin --delete "${BRANCH_NAME}"
          fi

          git checkout -b "${BRANCH_NAME}"

          git add "data/projects/${{ steps.generate_json.outputs.slug }}.json"
          
          git commit -m "Add project: ${{ steps.generate_json.outputs.slug }}"
          git push origin "${BRANCH_NAME}"


          
      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Create Pull Request
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Add new project: ${{ steps.generate_json.outputs.slug }}" \
            --body "This PR adds a new project file for the project slug ${{ steps.generate_json.outputs.slug }}." \
            --head "${BRANCH_NAME}" \
            --base "main"
