name: JSON Schema Validation

on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*.json' # Trigger the workflow for any JSON file changes in PRs
  workflow_dispatch:

jobs:
  validate:
    name: Validate JSON files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install JSON Schema Validator and Formats
        run: |
          npm install -g ajv-cli ajv-formats
      
      - name: Validate JSON files
        run: |
          ajv -c ajv-formats validate -s schema.json -d 'data/**/*.json' --strict=false
